CREATE TABLE COLLATERAL_SSI
(
  BROKER_ID              VARCHAR2(6 CHAR),
  PRODUCT_LINE           VARCHAR2(2 CHAR),
  SETTLEMENT_LOCATION    VARCHAR2(4 CHAR),
  HOUSE_ACCOUNT          VARCHAR2(4 CHAR),
  BROKER_ACCOUNT_NUMBER  VARCHAR2(20 CHAR),
  EXECUTING_BROKER       VARCHAR2(5 CHAR),
  CLEARING_BROKER        VARCHAR2(5 CHAR),
  EXECUTING_BIC          VARCHAR2(11 CHAR),
  CLEARING_BIC           VARCHAR2(11 CHAR),
  FED_MNEMONIC           VARCHAR2(10 CHAR),
  SSI_STATUS             VARCHAR2(2 CHAR),
  CREATE_BY              VARCHAR2(7 CHAR),
  CREATED_DATETIME       DATE,
  LAST_MODIFIED_BY       VARCHAR2(7 CHAR),
  LAST_MOD_DATETIME      DATE,
  APPROVED_BY            VARCHAR2(7 CHAR),
  APPROVED_DATETIME      DATE,
  BROKER_SUBACCOUNT      VARCHAR2(20 CHAR),
  DEPOSITORY_PART_CODE   VARCHAR2(20 CHAR),
  SEQ_NUM                NUMBER                 DEFAULT 1                     NOT NULL
  ACTIVITY 				 CHAR(1 CHAR)
)